### ISSUE TITLE
Auto send data layer not working. (Please Help ME MJ!)

### ISSUE THREAD

**Issue by PRINCEMOUSTAPHA** [Adsmurai-Google-Tag-Manager-Templates/adsmurai-facebook-pixel-and-conversions-api#19]
Hello. I decided to setup Facebook API & Web events using Adsmurai’s Web Tag, Server Client, and Server Tag. 

The system is perfect except for one thing. I noticed the EVENT DATA TAB in the server client never shows any information from the data layer EVERYTHING SAYS UNDEFINED . (Unless manually pulled from DATA LAYER) (SCREENSHOT ATTACHED)

The information IS being sent according to DATA LAYER  tab on the web tag (SCREENSHOT ATTACHED)

From my understanding  the Adsmurai web tag has an option to send all data layer information to the server client automatically with the option to overwrite. ( if I am comprehending the settings properly)

I have been using Stapes Data Tag and client, and the data layer is auto sent and received by the server also  shows information in all fields.

My question is if the data layer is supposed to be automatically sent and received by server client why does the server only show Information in EVENT DATA as filled out when I MANUALLY PULL from data layer?

THE FIRST SCREENSHOT IS FROM EVENT DATA IN THE SERVER CLIENT

THE SECOND SCREENSHOT IS FROM DATA LAYER TAB IN WEB TAG

THE INFORMATION SHOULD BE SHOWING ON SERVER SIDE AND THE MY PROBLEM TO SIMPLIFY/CLARIFY

<img width="792" alt="Screenshot 2024-04-19 at 6 12 12 PM" src="https://github.com/Adsmurai-Google-Tag-Manager-Templates/adsmurai-facebook-conversions-api-tag/assets/167690093/8c92af0c-c0fd-43a6-bd3d-71c82f5661ab">

<img width="481" alt="Screenshot 2024-04-19 at 6 12 05 PM" src="https://github.com/Adsmurai-Google-Tag-Manager-Templates/adsmurai-facebook-conversions-api-tag/assets/167690093/f35c3a51-89f2-4e4e-bc1a-cc9cbafba980">

**Comment by PRINCEMOUSTAPHA** [comment]
thank you for responding. I believe there may be a slight miscommunication. I read your response. 

1. I am already using the client you linked. please see photo below.

<img width="1680" alt="Screenshot 2024-04-29 at 9 05 15 AM" src="https://github.com/Adsmurai-Google-Tag-Manager-Templates/adsmurai-facebook-pixel-and-conversions-api/assets/167690093/b3d7005e-fcd3-4a7e-9079-15552676e9f2">

2. this is the web tag I am using - I only use it for Facebook. 
<img width="1680" alt="Screenshot 2024-04-29 at 9 03 27 AM" src="https://github.com/Adsmurai-Google-Tag-Manager-Templates/adsmurai-facebook-pixel-and-conversions-api/assets/167690093/439f03ff-2e91-49f9-874b-ae7d2acd8fa0">

3.  this is the server tag that I use

<img width="1680" alt="Screenshot 2024-04-29 at 9 07 16 AM" src="https://github.com/Adsmurai-Google-Tag-Manager-Templates/adsmurai-facebook-pixel-and-conversions-api/assets/167690093/06874d1e-063f-45f7-a520-c823bdef288d">


they work great together for sending events. all my events send to Facebook perfectly. but I the data layer information to automatically send to server client. are we on the same page?

**Comment by mjadsmurai** [comment]
Sorry, i clearly failed to explain myself properly :(
Some functionalities of this tag, like the one you're trying to use (grab data from dataLayer automatically) only work when the tag is pointing to OneTag service. It won't work on selfhosted servers.
That's because the way we process and send information on OneTag vs selfhosted is very differnt (way more data can be sent to OneTag, while selfhosted comms is quite limited).
That's also why on selfhosted servers only handle a single provider (Facebook) vs OneTag that has a more expanded list you can send at once.

**Comment by PRINCEMOUSTAPHA** [comment]
Okay I understand that. I have been reluctant to use onetag because I want full customization options. It does seem that there are still lots of features. I have a a few questions about one tag. I signed up for the trial just now. 

1. When testing events can we see exactly what the one to recived? So I can verify the information is received ?

2. How do I send a FBC with one tag?

3. My goal is to get a 10/10 matching score on all events so my pixel is that much more effective . To do that I need all the data points fb requests. 

4. Does it handle deduplication

**Comment by mjadsmurai** [comment]
`1. When testing events can we see exactly what the one to recived? So I can verify the information is received ?`
That will depend on the platform, in the tag you can set the test code for said platform and then on Facebook/tiktok/ you will be able to see the test events that you send and their data (some platforms like Linkedin aren't very helpful).

The advantage that you will have is that you will see a health summary on OneTag dashboard of all platforms. If there's any error or problem, the system will show you a sample event. So you can understand where and what's happening faster.

`2. How do I send a FBC with one tag?`
If you are talking about fbp and fbc cookies/params, those are sent automatically :)

`3. My goal is to get a 10/10 matching score on all events so my pixel is that much more effective . To do that I need all the data points fb requests.`

You will achieve that for sure.

`4. Does it handle deduplication`
Yes!

**Comment by PRINCEMOUSTAPHA** [comment]
I am testing one tag trial, I will let you know how I like the service. it said 30 day but only gave me 7. 

I see that you release updates frequently I love that!! . Is there any chance your will but updating web tag to send eccomerce  event data and customer data  auto to our own custom server any time soon?

**Comment by mjadsmurai** [comment]
`I am testing one tag trial, I will let you know how I like the service. it said 30 day but only gave me 7.`
Oh, that's because you get 30 day trial of AMP but OneTag is only 7 days. I've reported it to the web team so they can make the appropriate updates.

`I see that you release updates frequently I love that!! .`
Yes, we also add new providers as clients hire us to implement them.

` Is there any chance your will but updating web tag to send eccomerce  event data and customer data  auto to our own custom server any time soon?`
I don't think so. Doing it would require refactoring both components and going through all our existing clients to upgrade their templates manually so they don't just upgrade the server or the web and everything breaks :o
