### ISSUE TITLE
Using one single Adsmurai template for Facebook & Pinterest

### ISSUE THREAD

**Issue by EW0JY** [Adsmurai-Google-Tag-Manager-Templates/adsmurai-facebook-pixel-and-conversions-api#20]
Hi there,

I'm using OneTag and the Adsmurai GTM template to send "lead" and "subscribe" events to Facebook and Pinterest.

The tag fires on the same landing page.

When looking at the OneTag dashboard, it says "OK" to both types of events "lead" and "subscribe" being sent successfully to both parties.

However, since only Facebook understands the event type "subscribe", whereas Pinterest doesn't have that event, the subscribe events don't actually show up in Pinterest's Conversion dashboard - only the "lead" events go through.

So I have a couple of questions:

1) Since I can only select one event type in the Adsmurai GTM tag, but then put in the pixels for Facebook and Pinterest (and more) platforms, the same even type gets send to all of them - even if they don't necessarily expect or "understand" that event name.

Does this mean I need to create two GTM tags in my described scenario to be able to send the appropriate event type to each platform?

Or is there a way to do achieve this goal with one single Tag being fired?

2) How come the OneTag dashboard shows "OK" for the Pinterest "subscribe" event, when they evidently don't understand that event and don't accept it?

Thanks so much!

**Comment by mjadsmurai** [comment]
We do always send the events because details like conversion name understanding by those platforms tend to change and also because most platforms are smart enough to handle custom events.
If you don't want subscribe event to be sent to Pinterest, you will have to remove the pinterest pixel id from said event.

`How come the OneTag dashboard shows "OK" for the Pinterest "subscribe" event, when they evidently don't understand that event and don't accept it?`
We collect the response they give to us. If they tell us that everything was okay, that's what will appear :(

**Comment by EW0JY** [comment]
Ok, I see, that makes sense.

But just to make sure I interpret the results on FB an Pinterest correctly:

Let's say I have only one Adsmurai template set up in GTM, which fires a "lead" event to both Pinterest & Facebook when a user visits a certain page.

Let's further consider only one single visit by one actual visitor for now.

Is my understanding correct that this will show up on both platforms as a lead event?

Meaning I might think I had 2 visitors, one from Pinterest and one from FB, because their stats both show me one lead event.

Moreover, I cannot know whether that visitor came from Pinterest, Facebook or Google or somewhere else?

As far as I know, the platforms can only determine whether a visitor came from their platform to a landing page if you run ads on their platform to that page.

But if you don't, and for example just look at the tag / CAPI events, they also show "foreign" events, meaning from off-platform visitors?

Thanks so much!

**Comment by mjadsmurai** [comment]
```
Is my understanding correct that this will show up on both platforms as a lead event?

Meaning I might think I had 2 visitors, one from Pinterest and one from FB, because their stats both show me one lead event.

Moreover, I cannot know whether that visitor came from Pinterest, Facebook or Google or somewhere else?

As far as I know, the platforms can only determine whether a visitor came from their platform to a landing page if you run ads on their platform to that page.
```

That's the core of Conversion Attribution. You have to feed your events/conversions to any platform you're publishing ads so they can work on if said conversion can be attributed to them. So when you send the same event to several platforms, only 1 or 0 of them should attribute the conversion. They don't attribute to themselves all events you send to them.

They also have no interest in attributing conversions they didn't make, because if you think it's working, invest more and realize it doesn't, you will not only fully stop using them but also write about it online.
